### PR TITLE
replace unmaintained safemem::copy_over with slice::copy_within

### PR DESCRIPTION
**Pull request by syphar**
* the `safemem` library is [unmaintained][1]
* both `safemem::copy_over` and `slice::copy_within` use `ptr::copy` internally, so the performance impact should be minimal.
* `slice::copy_within` was added in rust 1.37.0, but I don't know if lol-html has an official MSRV

[1]: https://rustsec.org/advisories/RUSTSEC-2023-0081.html

### CODE REVIEW

**Review by rillian — APPROVED** [review]
Looks equivalent to me, FWIW.

**Comment by rillian** [comment]
CI failures are unrelated clippy warnings.

**Comment by inikulin** [comment]
Could you please rebase on top of your clippy fix?

**Comment by syphar** [comment]
> Could you please rebase on top of your clippy fix?

done

**Review by inikulin — APPROVED** [review]

**Comment by inikulin** [comment]
Thank you!

**Pull request merged**
